/**
 * Project: JARVIS Echo Assistant Backend
 * File: server.js
 * Description: Express.js server providing an Alexa Skill endpoint for 
 *              a deep-voiced AI assistant powered by Gemini, Groq, and OpenRouter.
 */

const express = require("express");
const { GoogleGenAI } = require("@google/genai");
const Groq = require("groq-sdk");
const OpenAI = require("openai");

const app = express();
app.use(express.json());

// ==========================================
// CONFIGURATION & CLIENT INITIALIZATION
// ==========================================

// Global conversation context (short-term memory for active sessions)
const conversationHistory = [];
const MAX_HISTORY_LENGTH = 10;

// Initialize AI API Clients
const ai = new GoogleGenAI(); // Reads process.env.GEMINI_API_KEY
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY || "" });
const openrouter = new OpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY || ""
});

// System Prompt definition for JARVIS identity
const SYSTEM_PROMPT = 
    "You are JARVIS, an extraordinarily intelligent, polite, concise, and helpful AI assistant. " +
    "Address the user as Vijay when appropriate. Keep responses succinct, sharp, and natural for " +
    "voice output. Avoid long bulleted lists, markdown symbols, or visual formatting.";

// ==========================================
// SSML FORMATTING HELPERS
// ==========================================

/**
 * Strips unsupported characters and wraps response in Amazon Polly Brian SSML tags.
 * @param {string} text Plain text generated by LLMs.
 * @returns {string} Formatted SSML payload.
 */
function formatJarvisSSML(text) {
    if (!text) return `<speak><voice name="Brian"><prosody pitch="-28%" rate="88%">Standing by, Vijay.</prosody></voice></speak>`;

    const cleanText = String(text)
        .replace(/[*_#`~]/g, "")         // Remove Markdown formatting symbols
        .replace(/&/g, "and")            // Replace ampersands for valid XML
        .replace(/</g, "")               // Strip opening XML angle brackets
        .replace(/>/g, "")               // Strip closing XML angle brackets
        .replace(/"/g, "")               // Remove double quote marks
        .replace(/\n+/g, " ")            // Convert newlines to simple pauses
        .trim();

    return `<speak><voice name="Brian"><prosody pitch="-28%" rate="88%">${cleanText}</prosody></voice></speak>`;
}

/**
 * Updates memory context array with newest user and assistant turns.
 * @param {string} role User or Assistant
 * @param {string} content Message content
 */
function pushHistory(role, content) {
    conversationHistory.push({ role, content });
    if (conversationHistory.length > MAX_HISTORY_LENGTH) {
        conversationHistory.shift();
    }
}

// ==========================================
// AI PROVIDER ROUTERS
// ==========================================

/**
 * Generates response using Google Gemini 2.5 Flash
 */
async function askGemini(prompt) {
    try {
        const fullPrompt = `${SYSTEM_PROMPT}\n\nUser Query: ${prompt}`;
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: fullPrompt
        });
        return response.text || "I processed your request, Vijay, but received no text output.";
    } catch (err) {
        console.error("[JARVIS Error - Gemini]:", err.message);
        return "I encountered a communication error with my Gemini subsystem, Vijay.";
    }
}

/**
 * Generates response using Groq LLaMA 3.3 70B
 */
async function askGroq(prompt) {
    try {
        const messages = [
            { role: "system", content: SYSTEM_PROMPT },
            ...conversationHistory,
            { role: "user", content: prompt }
        ];

        const response = await groq.chat.completions.create({
            messages: messages,
            model: "llama-3.3-70b-versatile",
            temperature: 0.7,
            max_tokens: 300
        });

        return response.choices[0]?.message?.content || "Groq returned an empty response, Vijay.";
    } catch (err) {
        console.error("[JARVIS Error - Groq]:", err.message);
        return "I am having difficulty connecting to my Groq primary core, Vijay.";
    }
}

/**
 * Generates response using OpenRouter endpoint
 */
async function askOpenRouter(prompt) {
    try {
        const messages = [
            { role: "system", content: SYSTEM_PROMPT },
            ...conversationHistory,
            { role: "user", content: prompt }
        ];

        const response = await openrouter.chat.completions.create({
            model: "meta-llama/llama-3.3-70b-instruct",
            messages: messages,
            temperature: 0.7,
            max_tokens: 300
        });

        return response.choices[0]?.message?.content || "OpenRouter returned an empty result, Vijay.";
    } catch (err) {
        console.error("[JARVIS Error - OpenRouter]:", err.message);
        return "My OpenRouter routing layer experienced an exception, Vijay.";
    }
}

// ==========================================
// ALEXA ROUTE HANDLER
// ==========================================

app.post("/alexa", async (req, res) => {
    try {
        const request = req.body.request;
        if (!request) {
            return res.status(400).json({ error: "Invalid Alexa payload structure." });
        }

        const requestType = request.type;
        console.log(`[JARVIS Log] Received request type: ${requestType}`);

        // Handle LaunchRequest ("Alexa, open My Jarvis")
        if (requestType === "LaunchRequest") {
            const welcomeText = "Online and operational, Vijay. How can I assist you today?";
            pushHistory("assistant", welcomeText);

            return res.json({
                version: "1.0",
                response: {
                    outputSpeech: {
                        type: "SSML",
                        ssml: formatJarvisSSML(welcomeText)
                    },
                    shouldEndSession: false
                }
            });
        }

        // Handle IntentRequest & Fallback Requests
        if (requestType === "IntentRequest") {
            const intentName = request.intent?.name;
            console.log(`[JARVIS Log] Processing Intent: ${intentName}`);

            if (intentName === "AskJarvisIntent" || intentName === "AMAZON.FallbackIntent") {
                let userQuery = request.intent?.slots?.query?.value || "Hello";
                let selectedProvider = "gemini"; // Default engine

                const lowerQuery = userQuery.toLowerCase();

                // Dynamic Model Switching logic
                if (lowerQuery.includes("groq")) {
                    selectedProvider = "groq";
                    userQuery = userQuery.replace(/ask groq|use groq|groq/gi, "").trim();
                } else if (lowerQuery.includes("openrouter")) {
                    selectedProvider = "openrouter";
                    userQuery = userQuery.replace(/ask openrouter|use openrouter|openrouter/gi, "").trim();
                } else if (lowerQuery.includes("gemini")) {
                    selectedProvider = "gemini";
                    userQuery = userQuery.replace(/ask gemini|use gemini|gemini/gi, "").trim();
                }

                if (!userQuery) userQuery = "Hello";
                pushHistory("user", userQuery);

                let aiReply = "";
                if (selectedProvider === "groq") {
                    aiReply = await askGroq(userQuery);
                } else if (selectedProvider === "openrouter") {
                    aiReply = await askOpenRouter(userQuery);
                } else {
                    aiReply = await askGemini(userQuery);
                }

                pushHistory("assistant", aiReply);

                return res.json({
                    version: "1.0",
                    response: {
                        outputSpeech: {
                            type: "SSML",
                            ssml: formatJarvisSSML(aiReply)
                        },
                        shouldEndSession: false
                    }
                });
            }

            // Handle Skill Cancellation / Exit Intents
            if (intentName === "AMAZON.StopIntent" || intentName === "AMAZON.CancelIntent") {
                return res.json({
                    version: "1.0",
                    response: {
                        outputSpeech: {
                            type: "SSML",
                            ssml: formatJarvisSSML("Powering down systems. Goodbye, Vijay.")
                        },
                        shouldEndSession: true
                    }
                });
            }
        }

        // Handle SessionEndedRequest
        if (requestType === "SessionEndedRequest") {
            console.log("[JARVIS Log] Session ended by user or system.");
            return res.json({
                version: "1.0",
                response: {
                    shouldEndSession: true
                }
            });
        }

        // Fallback response for unhandled intent types
        return res.json({
            version: "1.0",
            response: {
                outputSpeech: {
                    type: "SSML",
                    ssml: formatJarvisSSML("I am listening, Vijay.")
                },
                shouldEndSession: false
            }
        });

    } catch (error) {
        console.error("[JARVIS Critical Error]:", error);
        return res.json({
            version: "1.0",
            response: {
                outputSpeech: {
                    type: "SSML",
                    ssml: formatJarvisSSML("An unexpected failure occurred within my primary backend, Vijay.")
                },
                shouldEndSession: true
            }
        });
    }
});

// Health check endpoint for ngrok validation
app.get("/", (req, res) => {
    res.send("JARVIS Core Backend is active and online.");
});

// ==========================================
// SERVER INITIALIZATION
// ==========================================

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`==========================================`);
    console.log(`  JARVIS Server listening on port ${PORT}`);
    console.log(`  Endpoint route: http://localhost:${PORT}/alexa`);
    console.log(`==========================================`);
});
